#-*- coding: utf-8 -*-

#sciezka_pliku='C:\\Users\\Mały Araj\\Documents\\bazaDanych\\slowka\\'
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  database="tlumaczenia"
)
#f=open(sciezka_pliku+"doSql2.txt","r")
mycursor = mydb.cursor()

sql = "INSERT INTO podstawa(angielski, polski) VALUES (%s, %s)"

#for x in f:
#	val+=x
#print(val)
val = [
('able','w stanie, zdolny (do czegoś)'),
('about','o, około'),
('above','powyżej, ponad'),
('accept','przyjmować, akceptować'),
('account','konto'),
('acid','kwas, kwaśny'),
('across','przez, poprzez'),
('act','działać, postępować, akt'),
('add','dodawać'),
('addition','dodatek'),
('adjustment','regulacja'),
('advertisement','reklama'),
('after','po, później'),
('again','jeszcze raz, znowu'),
('against','wbrew, przeciwko'),
('age','wiek'),
('ago','przed, temu'),
('agreement','porozumienie, umowa'),
('air','powietrze'),
('all','wszystko, cały'),
('allow','pozwalać'),
('almost','prawie, niemal'),
('also','również'),
('always','zawsze, ciągle'),
('AM','przed południem'),
('among','wśród'),
('amount','ilość, liczba, kwota'),
('amusement','rozbawienie'),
('and','i, oraz'),
('angle','kąt, haczyk'),
('angry','rozgniewany, zły'),
('animal','zwierzę'),
('answer','odpowiedź'),
('ant','mrówka'),
('any','dowolny, jakikolwiek'),
('apparatus','narząd, sprzęt'),
('appear','pojawiać się, ukazywać się'),
('apple','jabłko'),
('approval','zatwierdzenie, aprobata, zgoda'),
('arch','łuk'),
('area','teren, obszar'),
('argument','spór, sprzeczka, polemika, argument'),
('arm','ręka, ramię'),
('army','wojsko, armia'),
('art','sztuka'),
('as','jak, jako'),
('ask','zapytać, poprosić'),
('at','przy, na, w'),
('attempt','próba, usiłowanie'),
('attention','baczność, uwaga, zainteresowanie'),
('attraction','przyciąganie, atrakcyjność, atrakcja'),
('authority','powaga, władza, autorytet, upoważnienie'),
('automatic','automatyczny, mechaniczny'),
('awake','czujny, przebudzony'),
('baby','niemowlę'),
('back','z powrotem, wstecz, plecy'),
('bad','zły, niegrzeczny'),
('bag','worek, torba, torebka'),
('balance','równowaga, balans'),
('ball','piłka, kłębek, kula'),
('band','zespół, kapela'),
('base','baza, podstawa'),
('basin','miednica, umywalka, misa'),
('basket','koszyk'),
('bath','wanna, kąpiel'),
('be','być'),
('beautiful','piękny'),
('beauty','piękno'),
('because','ponieważ, bo'),
('bed','łóżko'),
('bee','pszczoła'),
('before','przed, zanim'),
('begin','rozpocząć, zaczynać'),
('behaviour','zachowanie, postępowanie'),
('behind','za, z tyłu'),
('belief','wierzenie, przekonanie'),
('believe','wierzyć'),
('bell','dzwonek, dzwon'),
('bent','zgięty, zakrzywiony'),
('berry, blueberry','jagoda'),
('best','najlepszy'),
('better','lepiej'),
('between','pomiędzy'),
('bicycle, bike','rower'),
('big','duży'),
('bird','ptak'),
('birth','narodziny'),
('bit','kawałek, odłamek'),
('bite','gryźć, kąsać'),
('bitter','gorzki'),
('black','czarny'),
('blade','ostrze'),
('book','książka'),
('boot','bagażnik, but, botek'),
('borrow','pożyczyć (od kogoś)'),
('both','oba'),
('bottle','butelka'),
('box','pudełko'),
('boy','chłopiec'),
('brain','mózg'),
('brake','hamulec'),
('branch','gałąź, oddział (np. banku)'),
('brass','mosiądz'),
('bread','chleb'),
('break','złamać, przerwać, przerwa'),
('breath','oddech'),
('brick','cegła'),
('bridge','most'),
('bright','promienny, jasny'),
('bring','przynieść'),
('broken','zepsuty, złamany, rozbity'),
('brother','brat'),
('brown','brązowy, brunatny'),
('brush','szczotka'),
('buck','kozioł'),
('bucket','wiadro, kubeł'),
('build','budować'),
('building','budowla, budynek'),
('bulb','żarówka, bulwa, cebulka'),
('burst','pękać, wybuchać'),
('business','biznes'),
('busy','zajęty'),
('but','ale, lecz'),
('butter','masło'),
('button','przycisk'),
('buy','kupować'),
('by','przez'),
('cake','ciasto, ciastko'),
('call','wołać, nazywać, dzwonić do kogoś'),
('camera','kamera, aparat fotograficzny'),
('can','móc, umieć, potrafić'),
('cancel','anuluj, anulować'),
('canvas','płótno'),
('car','samochód'),
('card','karta'),
('care','opieka'),
('carriage','wagon'),
('carry','nosić, wiązać się z'),
('cart','wóz'),
('cat','kot'),
('cause','powód, przyczyna'),
('center','ośrodek'),
('blood','krew'),
('blow','wiać, dmuchać'),
('blue','niebieski'),
('board','płyta, deska, tablica'),
('boat','łódź, statek'),
('body','ciało'),
('boiling','wrzenie, gotowanie'),
('bone, fishbone','kość, ość'),
('certain','pewny, pewien'),
('chain','łańcuch, sieć'),
('chalk','kreda'),
('chance','przypadek, okazja, szansa'),
('change','zmiana, zmieniać, reszta'),
('cheap','tani'),
('check','sprawdzać, rachunek'),
('cheese','ser'),
('chemical','chemiczny'),
('chest','skrzynia, kufer, klatka piersiowa'),
('chief','naczelnik, dyrektor, szef'),
('children','dzieci'),
('chin','broda, podbródek'),
('church','kościół'),
('circle','koło'),
('city','duże miasto'),
('class','klasa, lekcja'),
('clean','czysty'),
('clear','jasny, wyraźny, czysty'),
('clock','zegar'),
('close','blisko, zamykać'),
('cloth','materiał, tkanina, ścierka, obrus'),
('cloud','chmura'),
('coal','węgiel'),
('coat','płaszcz, powłoka'),
('cold','przeziębienie, zimny'),
('collar','kołnierz, obroża'),
('color','kolor'),
('colour','kolor'),
('comb','grzebień'),
('come','przyjść, przyjechać'),
('comfort','komfort'),
('committee','komisja, komitet'),
('common','zwykły, częsty, pospolity'),
('company','przedsiębiorstwo, firma'),
('comparison','porównanie'),
('competition','rywalizacja, konkurs'),
('complain','skarżyć się, narzekać'),
('complete','kompletny'),
('complex','kompleks'),
('condition','warunek, stan'),
('connection','połączenie, związek'),
('conscious','przytomny, świadomy'),
('control','kontrola'),
('cook','kucharz'),
('copper','miedziany, miedź'),
('copy','kopia, reprodukcja'),
('cord','sznur, sznurek'),
('cork','korek'),
('correct','prawidłowy'),
('cotton','wata, bawełna'),
('cough','kaszel'),
('count','liczyć'),
('country','kraj, wieś'),
('course','kurs, bieg'),
('cover','przykryć, chować, okładka'),
('cow','krowa'),
('crack','pęknięcie'),
('credit','kredyt, uznanie, zaufanie'),
('crime','przestępstwo, zbrodnia, przestępczość'),
('cross','krzyż'),
('cruel','okrutny'),
('crush','miażdżyć'),
('cry','płakać'),
('cup','filiżanka, puchar'),
('current','aktualny, bieżący'),
('curtain','zasłona, firanka, kurtyna'),
('curve','krzywa, łuk, zakręt'),
('cushion','poduszka, zamortyzować'),
('cut','cięcie'),
('damage','uszkodzenie, szkoda'),
('dance','taniec'),
('danger','zagrożenie, niebezpieczeństwo'),
('dark','ciemny, tajemniczy, mroczny'),
('daughter','córka'),
('day','dzień, doba'),
('dead','martwy'),
('dear','kochany'),
('death','śmierć'),
('debt','dług'),
('decision','postanowienie, decyzja'),
('deep','głęboki'),
('degree','stopień (np. naukowy)'),
('delicate','delikatny'),
('dependent','zależny, podległy, zawisły'),
('design','konstrukcja, projekt, zamysł'),
('desire','pragnienie, chęć'),
('destruction','zniszczenie'),
('detail','szczegół'),
('development','rozwój, rozwinięcie'),
('differ','różnić się'),
('different','różny, inny'),
('digestion','trawienie'),
('direct','bezpośredni'),
('direction','kierunek'),
('dirty','brudny'),
('discovery','odkrycie'),
('discussion','dyskusja'),
('disease','choroba'),
('disgust','obrzydzenie, wstręt'),
('distance','dystans, odległość'),
('distribution','dystrybucja'),
('division','dzielenie, podział'),
('do','robić'),
('dog','pies'),
('done','zrobiony'),
('door','drzwi'),
('doubt','wątpliwość'),
('down','w dół'),
('drain','odpływ, rura kanalizacyjna'),
('draw','rysować, remis'),
('drawer','szuflada'),
('dress','suknia'),
('drink','pić'),
('drive','prowadzić (np. samochód)'),
('driving','jazda, powożenie'),
('drop','upadek, zrzut, kropla'),
('dry','suchy'),
('during','podczas'),
('dust','kurz, pył'),
('ear','ucho'),
('early','wcześnie'),
('Earth','ziemia'),
('ease','łatwość'),
('east','wschód'),
('eat','jeść'),
('edge','krawędź, brzeg, skraj, ostrze'),
('education','edukacja, wykształcenie'),
('effect','skutek, wpływ, efekt'),
('egg','jajko'),
('elastic','elastyczny, sprężysty'),
('electric','elektryczny'),
('end','koniec'),
('engine','silnik, lokomotywa'),
('enough','wystarczająco, dość'),
('equal','równy'),
('error','błąd'),
('even','parzysty, równy, nawet'),
('event','wydarzenie'),
('ever','kiedykolwiek, kiedyś, nigdy'),
('every','każdy (z grupy)'),
('ex','były'),
('example','przykład'),
('exchange','wymiana'),
('existence','byt, istnienie'),
('expansion','ekspansja, rozwój, rozbudowa'),
('experience','doświadczenie, praktyka'),
('expert','ekspert'),
('explain','wyjaśniać'),
('eye','oko face'),
('fact','fakt'),
('fall','spadek'),
('false','fałszywy, sztuczny'),
('family','rodzina'),
('far','daleko'),
('farm','farma, gospodarstwo'),
('fast','szybki'),
('fat','gruby'),
('father','ojciec'),
('fear','obawa, strach'),
('feather','pióro'),
('feeble','marny, słaby'),
('feel','czuć, odczuwać, dotykać'),
('feeling','uczucie, odczucie, czucie'),
('feet','stopy'),
('female','żeński'),
('fertile','płodny'),
('few','kilka, mało, niewiele'),
('fiction','beletrystyka, fikcja'),
('field','pole'),
('fight','walka, walczyć'),
('final','finałowy, ostatni'),
('find','znaleźć, odkryć'),
('finger','palec u ręki'),
('fire','ogień, pożar, strzelać'),
('first','pierwszy'),
('fish','ryba'),
('fit','pasować'),
('five','pięć'),
('fixed','ustalony, stały'),
('flag','flaga, chorągiewka'),
('flame','płomień'),
('flat','mieszkanie, płaski'),
('flight','lot'),
('floor','piętro, podłoga, dno'),
('flower','kwiat'),
('fly','latać'),
('fold','zginać, składać'),
('food','jedzenie, żywność'),
('foolish','głupi'),
('for','dla, do, za'),
('force','siła, moc, zmusić'),
('forget','zapominać'),
('fork','widelec'),
('form','forma, formularz'),
('forward','naprzód'),
('found','znaleziony'),
('four','cztery'),
('fowl, poultry','drób'),
('frame','rama, ramka'),
('free','wolny'),
('frequent','częsty'),
('friend','przyjaciel, znajomy, kolega'),
('from','z, ze, od'),
('front','front, fasada'),
('fruit','owoc'),
('full','pełny, przepełniony, wypchany'),
('future','przyszłość'),
('game','gra, mecz, zabawa'),
('garden','ogród'),
('general','ogólny, generalny'),
('get','dostać, otrzymać, zdobyć'),
('girl','dziewczyna, dziewczynka'),
('give','dać, podać, nadać'),
('glass','szklanka, kieliszek, szkło'),
('glove','rękawiczka'),
('go','jechać, iść'),
('gold','złoto'),
('good','dobry'),
('govern','rządzić'),
('government','rząd'),
('grain','zboże, ziarno, ziarnko, odrobina'),
('grass','trawa'),
('great','wielki, ogromny, wspaniały'),
('green','zielony'),
('grey','szary, siwy'),
('grip','uchwyt, opanować'),
('group','grupa, gromada'),
('growth','wzrost, rozwój'),
('guide','przewodnik, poradnik'),
('gun','pistolet'),
('hair','włos, włosy, sierść'),
('half','połowa'),
('hammer','młot'),
('hand','ręka, dłoń'),
('hanging','wiszące, nachylenie, powieszenie zbrodniarza'),
('happen','zdarzać się, dziać się'),
('happy','szczęśliwy'),
('harbour','port, przystań'),
('hard','ciężko, twardo, silnie'),
('harmony','harmonia'),
('hat','kapelusz'),
('hate','nienawidzić'),
('have','mieć, posiadać'),
('he','on'),
('head','głowa'),
('healthy','zdrowy'),
('hearing','słuch, przesłuchanie'),
('heart','serce'),
('heat','upał'),
('help','pomoc, wsparcie'),
('her','ją, jej'),
('here','tu, tutaj'),
('high','wysoki'),
('him','go'),
('his','jego'),
('history','historia, dzieje'),
('hole','otwór, dziura'),
('hollow','wydrążenie, wgłębienie'),
('home','dom rodzinny'),
('hook','hak, haczyk'),
('horn','klakson, róg'),
('horse','koń'),
('hose','wąż ogrodowy'),
('hospital','szpital'),
('hot','gorący, gorąco'),
('hour','godzina'),
('house','dom'),
('how','jak, ile'),
('humour','humor'),
('hundred','sto'),
('hurtle','pognać, popędzić'),
('I','ja'),
('ice cream','lody'),
('idea','pomysł'),
('if','jeśli, czy'),
('ill','chory, cierpiący'),
('important','ważny'),
('impulse','impuls'),
('in','w'),
('inch','cal'),
('increase','wzrost, zwiększenie, wzmożenie'),
('industry','przemysł, pilność'),
('ink','atrament'),
('insect','owad'),
('instrument','instrument, narzędzie, przyrząd'),
('insurance','ubezpieczenie'),
('interest','zainteresowanie'),
('invention','wynalazek, inwencja'),
('iron','żelazo'),
('island','wyspa'),
('it','to, ono'),
('jelly','galaretka'),
('jewel','klejnot'),
('join','spojenie, przyłączyć się do czegoś'),
('journey','podróż, wędrówka'),
('judge','sędzia'),
('jump','skakać'),
('just','tylko, właśnie, po prostu'),
('keep','zachować, trzymać, dotrzymywać'),
('kettle','czajnik, imbryk'),
('key','klucz'),
('kick','kopać, skopać, wykopać'),
('kind','rodzaj, uprzejmy'),
('king','król'),
('kiss','pocałunek'),
('knee','kolano'),
('knife','nóż'),
('knot','węzeł, supeł'),
('knowledge','wiedza, znajomość'),
('land','ląd, lądować'),
('language','język'),
('large','duży, wielki'),
('last','ostatni, ubiegły'),
('late','późny'),
('laugh','śmiać się'),
('law','prawo, przepis, ustawa'),
('lay','kłaść, położyć'),
('lead','prowadzić, ołów'),
('learn','uczyć się'),
('learning','wiedza, uczenie się'),
('leather','skórzany, skóra'),
('leave','wyjechać, opuszczać, zostawić'),
('left','lewy, lewo'),
('leg','noga, nogawka'),
('let','pozwolić, wynająć'),
('letter','list, litera'),
('level','poziom'),
('library','biblioteka'),
('life','życie'),
('lift','wznieść ,podwiezienie, wyciąg, winda'),
('light','światło, jasność'),
('like','lubić, tak jak'),
('limit','limit'),
('line','linia'),
('lineage','ród, pochodzenie'),
('linen','płótno lniane, bielizna pościelowa'),
('lip','warga'),
('liquid','ciecz, płyn'),
('list','lista, spis'),
('listen','słuchać'),
('little','trochę, mało'),
('live','żyć, mieszkać'),
('living','życie, utrzymanie'),
('lock','zamykać'),
('long','długi'),
('look','wyglądać, patrzeć'),
('loose','luźny, obluzowany, rozluźniony'),
('loss','strata, przegrana'),
('loud','głośny'),
('low','niski'),
('machine','maszyna'),
('make','zrobić'),
('male','męski'),
('man','człowiek, mężczyzna'),
('manager','kierownik'),
('map','mapa'),
('mark','znak, oznaczenie, zanotować'),
('market','rynek'),
('married','żonaty, zamężna, małżeński'),
('mass','masa, msza, bryła'),
('material','tworzywo, materia, tkanina'),
('may','móc'),
('me','mnie'),
('meal','posiłek, mąka'),
('measure','miara'),
('meat','mięso'),
('medical','medyczny, lekarski, sanitarny'),
('meeting','zebranie, spotkanie'),
('memory','pamięć, wspomnienie'),
('men','mężczyźni'),
('metal','metal'),
('mid','średni'),
('middle','środek'),
('might','potęga'),
('mile','mila'),
('military','wojskowy'),
('milk','mleko'),
('mind','umysł'),
('mine','mój'),
('minute','minuta'),
('miss','chybić'),
('mist','mgiełka'),
('mixed','mieszany, zróżnicowany, koedukacyjny'),
('money','pieniądze'),
('monkey','małpa'),
('month','miesiąc'),
('moon','księżyc'),
('more','bardziej'),
('morning','ranek'),
('mother','matka'),
('motion','ruch, wniosek'),
('mountain','góra, górski'),
('mouth','usta'),
('move','przenieść, poruszać, ruch'),
('much','wiele, znacznie, sporo'),
('muscle','mięsień'),
('music','muzyka'),
('my','mój'),
('nail','paznokieć'),
('name','nazwa, imię'),
('narrow','wąski'),
('nation','naród'),
('natural','naturalny, wrodzony'),
('near','blisko'),
('necessary','konieczny'),
('neck','szyja, kark'),
('need','potrzeba'),
('needle','igła'),
('nerve','nerw, czelność, tupet'),
('net','sieć'),
('never','nigdy'),
('new','nowy'),
('news','nowiny, wiadomości'),
('night','noc'),
('no','nie, bez, żaden'),
('noise','hałas'),
('non','nie'),
('normal','normalny'),
('north','północ'),
('nose','nos'),
('not','nie'),
('note','zapisek'),
('nothing','nic'),
('notice','zawiadomienie'),
('noun','rzeczownik'),
('now','teraz, obecnie'),
('number','numer'),
('numeral','cyfra'),
('nut','nakrętka, orzech'),
('object','obiekt'),
('observation','spostrzegawczość, obserwacja, spostrzeżenie'),
('of','z, ze'),
('off','poza, od'),
('offer','oferta'),
('office','biuro, urząd'),
('often','często'),
('oh','och'),
('oil','olej, ropa'),
('old','stary, dawny'),
('on','na, w, nad'),
('one','jeden'),
('only','tylko'),
('open','otwarty'),
('operation','operacja, działanie'),
('opinion','zdanie, opinia'),
('opposite','naprzeciwko'),
('or','albo, lub'),
('orange','pomarańcza'),
('order','zamówienie, porządek, kolejność'),
('organization','organizacja'),
('ornament','ozdoba'),
('other','inny, odmienny'),
('our','nasz'),
('out','na zewnątrz, aut'),
('out','aut'),
('oven','piekarnik'),
('over','nad, ponad'),
('own','własny'),
('owner','właściciel'),
('page','strona, stronica'),
('pain','ból, cierpienie'),
('paint','malować, farba'),
('paper','papier, gazeta, referat naukowy'),
('parallel','równolegle'),
('part','część, udział, strona w sporze'),
('pass','zdać (np. egzamin), przepustka'),
('past','przeszłość'),
('paste','pasta, ciasto, przykleić'),
('pattern','wzór, wzorzec, wykrój, szablon'),
('pay','płaca, płacić'),
('payment','zapłata, płatność, wypłata'),
('peace','pokój, spokój'),
('pen','pióro, długopis'),
('pencil','ołówek'),
('people','ludzie, mieszkańcy, obywatele'),
('perhaps','być może, możliwe'),
('person','osoba'),
('physical','fizyczny, materialny'),
('picture','obraz, rysunek, zdjęcie, fotografia'),
('piece','kawałek'),
('pig, swine','świnia'),
('pin','przypiąć, szpilka'),
('pipe','rura, fajka'),
('place','miejsce'),
('plain','zwykły, prosty'),
('plane','samolot'),
('plant','roślina, fabryka'),
('plate','talerz, płyta'),
('play','grać, sztuka teatralna'),
('please','proszę, podobać się, prosić'),
('pleasure','przyjemność, zadowolenie'),
('plough','pług'),
('pocket','kieszeń'),
('point','punkt'),
('poison','jad, trucizna'),
('polish','polerować'),
('political','polityczny'),
('poor','biedny, ubogi'),
('port','port'),
('porter','tragarz, bagażowy'),
('position','położenie, stanowisko, pozycja'),
('possible','możliwy'),
('pot','garnek, dzbanek, doniczka'),
('potato','ziemniak, kartofel'),
('pound','funt'),
('powder','proszek, puder'),
('power','moc, siła'),
('present','obecny, teraźniejszy'),
('press','naciskać, prasa'),
('price','cena'),
('print','drukować, druk'),
('prison, jail','więzienie'),
('private','prywatny'),
('probable','prawdopodobny'),
('problem','problem, kłopot'),
('process','proces'),
('produce','produkować, wytwarzać'),
('product','produkt, iloczyn'),
('profit','zysk'),
('property','własność, mienie'),
('prose','proza'),
('protest','protest, bunt'),
('public','publiczny, społeczny'),
('pull','ciągnąć'),
('pump','pompa'),
('punishment','kara'),
('purpose','zamiar, cel'),
('push','pchać, pchnięcie'),
('put','położyć, kłaść, stawiać'),
('quality','jakość, gatunek, cecha'),
('question','pytanie'),
('quick','szybki, prędki'),
('quiet','cichy'),
('quite','całkiem, zupełnie, wcale'),
('rail','poręcz, szyna'),
('rain','deszcz'),
('range','zakres, zasięg'),
('rat','szczur'),
('rate','wskaźnik, współczynnik'),
('ray','promień'),
('reaction','reakcja'),
('read','czytać'),
('reading','lektura, czytanie'),
('ready','gotowy'),
('real','prawdziwy, rzeczywisty'),
('reason','powód, przyczyna, rozsądek, rozum'),
('receipt','pokwitowanie, kwit, paragon'),
('record','płyta, nagrywać'),
('red','czerwony, rudy'),
('regular','regularny, stały'),
('relation','stosunek, krewny, związek, relacja'),
('religion','religia'),
('remember','pamiętać'),
('representative','przedstawiciel, agent, reprezentant'),
('request','prośba'),
('respect','respekt, szacunek'),
('responsible','odpowiedzialny'),
('rest','reszta, odpoczynek'),
('reward','nagroda'),
('rhythm','rytm'),
('rice','ryż'),
('right','poprawny, prawo do czegoś, prawo (strona)'),
('ring','ring, pierścień, krąg, koło'),
('river','rzeka'),
('road','droga, ulica'),
('rock','skała'),
('roll','rolka, rulon'),
('roof','dach'),
('room','pokój'),
('root','korzeń'),
('rough','szorstki'),
('round','okrągły'),
('rub','pocierać, trzeć'),
('rule','reguła, zasada'),
('run','biec, uruchomić, bieg'),
('sad','smutny'),
('safe','bezpieczny, sejf'),
('sail','żagiel'),
('salt','sól'),
('same','taki sam'),
('saw','piła'),
('say','powiedzieć, mówić'),
('scale','waga, skala, podziałka'),
('school','szkoła'),
('science','nauka (ścisła)'),
('scissors','nożyczki'),
('screw','śruba, wkręt'),
('sea','morze'),
('seat','miejsce, siedzenie, siodełko, siedziba'),
('second','drugi, sekunda'),
('secondary','drugorzędny'),
('secret','tajemnica'),
('secretary','sekretarka, sekretarz'),
('see','zobaczyć, widzieć'),
('seed','nasienie, ziarno'),
('seem','wydawać się'),
('selection','selekcja, wybór, dobór'),
('self','siebie, ja, jaźń'),
('sell','sprzedawać'),
('send','wysyłać, przysyłać'),
('sense','zmysł'),
('sentence','zdanie, wyrok'),
('separate','oddzielny'),
('serious','poważny'),
('servant','służący'),
('serve','serwis, obsługiwać (np. klientów)'),
('several','kilka'),
('sex','płeć, seks'),
('shade','cień, odcień'),
('shake','potrząśnięcie'),
('shame','wstyd'),
('shape','kształt'),
('sharp','ostry, bystry'),
('she','ona'),
('sheep','owca'),
('shelf','półka'),
('ship','statek'),
('shirt','koszula'),
('shock','szok, wstrząs'),
('shoe','but, podkowa'),
('short','krótki, niski'),
('shut','zamknięty, zamknąć'),
('sick','chory'),
('side','bok, strona'),
('sign','znak'),
('silk','jedwab'),
('silver','srebro'),
('simple','prosty, zwyczajny'),
('sing','śpiewać'),
('sister','siostra'),
('sit','siad'),
('six','sześć'),
('size','rozmiar, numer, wielkość'),
('skin','skóra, skórka, łupina'),
('skirt','spódnica'),
('sky','niebo'),
('sleep','sen, spać'),
('slip','wsunąć, poślizgnąć się'),
('slope','zbocze, nachylenie'),
('slow','powolny, leniwy, opieszały'),
('small','mały'),
('smash','rozwalać'),
('smell','zapach, woń'),
('smile','uśmiech'),
('smoke','palić, dymić'),
('smooth','gładki, płynny'),
('sneeze','kichnięcie'),
('snow','śnieg'),
('so','tak, taki, więc, też, również'),
('soap','mydło'),
('society','społeczeństwo, towarzystwo'),
('sock','skarpetka'),
('soft','miękki, delikatny'),
('solid','stały, solidny'),
('some','kilka, część, około, jakiś'),
('son','syn'),
('song','pieśń, piosenka, śpiew'),
('soon','wkrótce, szybko, zaraz'),
('sort','rodzaj, gatunek'),
('sound','dźwięk'),
('soup','zupa'),
('south','południe'),
('space','miejsce, przestrzeń, odstęp, kosmos'),
('spade','rydel, łopata'),
('special','specjalny'),
('spell','zaklęcie'),
('sponge','gąbka'),
('spoon','łyżka'),
('spring','wiosna'),
('square','kwadrat, plac, pole'),
('stage','etap, stadium, faza'),
('stamp','znaczek, stempel'),
('stand','trybuna'),
('star','gwiazda'),
('start','start, początek'),
('statement','twierdzenie, oświadczenie'),
('station','stacja'),
('stay','pobyt'),
('steam','para, energia'),
('steel','stal'),
('stem','łodyga'),
('stick','trzymać, kij, pręt'),
('sticky','lepki'),
('stiff','sztywny'),
('still','wciąż, mimo to'),
('stitch','szew'),
('stocking','pończocha'),
('stomach','żołądek, brzuch'),
('stone','kamień'),
('stop','stop, zatrzymać, przestać'),
('store','przechowywać, sklep, skład'),
('story','opowieść'),
('straight','prosto, równo'),
('strange','obcy, nieznajomy, dziwny'),
('street','ulica'),
('stretch','rozciągać'),
('strong','silny, mocny'),
('structure','struktura, budowla, konstrukcja'),
('study','gabinet, pracownia'),
('substance','substancja'),
('such','taki, podobny'),
('sudden','nagły, gwałtowny'),
('sugar','cukier'),
('suggestion','propozycja'),
('summer','lato'),
('sun','słońce'),
('support','wsparcie, poparcie'),
('surface','powierzchnia'),
('surprise','niespodzianka'),
('sweet','słodki, łagodny, błogi'),
('swim','pływać'),
('system','system'),
('table','klasyfikacja, stół, tabela'),
('tail','ogon'),
('take','wziąć, brać'),
('talk','mówić, gadać'),
('tall','wysoki'),
('taste','smak, gust'),
('tax','podatek'),
('teach','uczyć'),
('teaching','nauczanie'),
('ten','dziesięć'),
('tendency','skłonność, tendencja'),
('test','test, badanie, próba'),
('than','niż'),
('that','tamten, tamta, tamto (o przedmiocie poza naszym zasięgiem)'),
('the','przedimek określony przed rzeczownikami'),
('their','ich'),
('them','ich, je, nimi, nich'),
('then','wtedy, następnie, w takim razie, a więc'),
('theory','teoria'),
('there','tam'),
('these','ci'),
('they','oni, one'),
('thick','gruby, ciężki'),
('thin','cienki'),
('thing','rzecz'),
('think','myśleć'),
('this','to, ten'),
('those','tamci'),
('though','chociaż, aczkolwiek'),
('thought','myśl, refleksja'),
('thousand','tysiąc'),
('thread','gwint, wątek'),
('three','trzy'),
('throat','gardło'),
('through','przez, poprzez'),
('thumb','kciuk'),
('thunder','grzmot'),
('ticket','bilet, mandat'),
('tight','ciasny, obcisły (o ubraniu)'),
('till','do'),
('time','czas, pora, raz'),
('tin','cyna, puszka'),
('tired','zmęczony'),
('to','do, na, aby'),
('toe','palec u nogi'),
('together','razem'),
('tomorrow','jutro'),
('tongue','język'),
('too','zbyt, także, również'),
('tooth','ząb'),
('top','góra, szczyt'),
('touch','dotyk, kontakt'),
('toward','w kierunku'),
('town','miasto'),
('trade','handel, zawód, branża'),
('train','trenować, pociąg'),
('translate','tłumaczyć'),
('transport','transport, przewóz'),
('travel','podróżować'),
('tray','taca'),
('tree','drzewo'),
('trick','trik'),
('trouble','kłopot, problem'),
('trousers','spodnie'),
('true','prawdziwy, wierny'),
('turn','skręcić, obracać'),
('twist','twist, skręcenie, zakręt'),
('two','dwa'),
('type','pisać na maszynie, typ, rodzaj'),
('umbrella','parasol'),
('under','pod, według, w trakcie'),
('understand','rozumieć'),
('unit','jednostka'),
('until','aż do, dopóki'),
('up','w górę, do góry, wyżej'),
('us','nas, nam'),
('use','korzystać, używać'),
('usual','zwykły'),
('value','wartość'),
('verse','wiersz, zwrotka'),
('very','bardzo'),
('vessel','statek, naczynie, pojemnik'),
('view','widok'),
('violent','gwałtowny'),
('voice','głos'),
('vowel','samogłoska'),
('waiting','czekanie'),
('walk','spacer, chód'),
('wall','ściana, mur'),
('war','wojna'),
('warm','ciepły'),
('wash','umyć, myć, prać'),
('waste','marnować, strata'),
('watch','obserwować, przyglądać'),
('water','woda (napój)'),
('wave','fala'),
('wax','wosk'),
('way','droga, strona, kierunek, sposób'),
('we','my'),
('weather','pogoda'),
('week','tydzień'),
('weight','odważnik, waga, ciężar'),
('well','dobrze, łatwo'),
('west','zachód'),
('wet','mokro, mokry'),
('what','co, jaki'),
('wheel','koło, kółko'),
('when','kiedy'),
('where','gdzie, dokąd'),
('wherever','gdziekolwiek'),
('which','który'),
('while','podczas, znowu'),
('whip','bicz, bat'),
('whistle','gwizdek'),
('white','biały'),
('who','kto, który'),
('why','dlaczego'),
('wide','szeroki, rozległy'),
('will','testament, wola, będzie'),
('wind','wiatr'),
('window','okno'),
('wine','wino'),
('wing','skrzydło'),
('winter','zima'),
('wire','drut, przewód'),
('wise','mądry, rozsądny'),
('with','z, ze'),
('woman','kobieta, pani'),
('wonder','zdumienie, cud, zastanawiać się'),
('wood','drzewo, drewno'),
('wool','wełna'),
('word','słowo, wyraz'),
('work','pracować, działać, robić'),
('world','świat'),
('worm','robak'),
('wound','rana, okaleczenie'),
]

mycursor.executemany(sql, val)

mydb.commit()

print(mycursor.rowcount, "was inserted.")

#f.close()
